/*
* generated by Xtext
*/
package org.xtext.example.helloscoping.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class HelloScopingAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/xtext/example/helloscoping/parser/antlr/internal/InternalHelloScoping.tokens");
	}
}
