/*
* generated by Xtext
*/
package org.xtext.example.helloscoping.ui.contentassist;

import org.xtext.example.helloscoping.ui.contentassist.AbstractHelloScopingProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class HelloScopingProposalProvider extends AbstractHelloScopingProposalProvider {

}
