/*
 * generated by Xtext
 */
package org.xtext.example.helloscoping;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class HelloScopingRuntimeModule extends org.xtext.example.helloscoping.AbstractHelloScopingRuntimeModule {

}
