/*
 * generated by Xtext
 */
package org.xtext.example.helloscoping.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class HelloScopingUiModule extends org.xtext.example.helloscoping.ui.AbstractHelloScopingUiModule {
	public HelloScopingUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
