/*
* generated by Xtext
*/
package org.xtext.example.helloscoping;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class HelloScopingUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.example.helloscoping.ui.internal.HelloScopingActivator.getInstance().getInjector("org.xtext.example.helloscoping.HelloScoping");
	}
	
}
